# Generated by Django 4.2.7 on 2023-11-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedEmailTasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255)),
                ("exc", models.TextField()),
                ("args", models.JSONField()),
                ("kwargs", models.JSONField()),
                ("einfo", models.TextField()),
            ],
        ),
    ]
